feat(@schematics/angular): remove useless import for Ivy
Using cli `6.2.0-beta.2` with the new `experimentalIvy` flag leads to:

    ERROR in src/app/app.module.ts(1,1): error TS6133: 'BrowserModule' is declared but its value is never read.