build: refresh AJV in lock file to fix typings error
```
packages/angular_devkit/core/src/json/schema/registry.ts:101:19 - error TS2345: Argument of type 'import("/home/circleci/ng/node_modules/ajv/dist/ajv").default' is not assignable to parameter of type 'import("/home/circleci/ng/node_modules/ajv-formats/node_modules/ajv/dist/core").default'.
  Types of property 'opts' are incompatible.
    Type 'import("/home/circleci/ng/node_modules/ajv/dist/core").InstanceOptions' is not assignable to type 'import("/home/circleci/ng/node_modules/ajv-formats/node_modules/ajv/dist/core").InstanceOptions'.
      Type 'InstanceOptions' is not assignable to type 'CurrentOptions'.
        Types of property 'keywords' are incompatible.
          Type 'import("/home/circleci/ng/node_modules/ajv/dist/types/index").Vocabulary | undefined' is not assignable to type 'import("/home/circleci/ng/node_modules/ajv-formats/node_modules/ajv/dist/types/index").Vocabulary | undefined'.
            Type 'import("/home/circleci/ng/node_modules/ajv/dist/types/index").Vocabulary' is not assignable to type 'import("/home/circleci/ng/node_modules/ajv-formats/node_modules/ajv/dist/types/index").Vocabulary'.
              Type 'string | import("/home/circleci/ng/node_modules/ajv/dist/types/index").KeywordDefinition' is not assignable to type 'string | import("/home/circleci/ng/node_modules/ajv-formats/node_modules/ajv/dist/types/index").KeywordDefinition'.
                Type 'CodeKeywordDefinition' is not assignable to type 'string | KeywordDefinition'.
                  Type 'import("/home/circleci/ng/node_modules/ajv/dist/types/index").CodeKeywordDefinition' is not assignable to type 'import("/home/circleci/ng/node_modules/ajv-formats/node_modules/ajv/dist/types/index").CodeKeywordDefinition'.
                    Types of property 'code' are incompatible.
                      Type '(cxt: import("/home/circleci/ng/node_modules/ajv/dist/compile/validate/index").KeywordCxt, ruleType?: string | undefined) => void' is not assignable to type '(cxt: import("/home/circleci/ng/node_modules/ajv-formats/node_modules/ajv/dist/compile/validate/index").KeywordCxt, ruleType?: string | undefined) => void'.
                        Types of parameters 'cxt' and 'cxt' are incompatible.
                          Type 'import("/home/circleci/ng/node_modules/ajv-formats/node_modules/ajv/dist/compile/validate/index").KeywordCxt' is not assignable to type 'import("/home/circleci/ng/node_modules/ajv/dist/compile/validate/index").KeywordCxt'.
                            The types of 'gen._scope' are incompatible between these types.
                              Type 'import("/home/circleci/ng/node_modules/ajv-formats/node_modules/ajv/dist/compile/codegen/scope").Scope' is not assignable to type 'import("/home/circleci/ng/node_modules/ajv/dist/compile/codegen/scope").Scope'.
                                Property '_names' is protected but type 'Scope' is not a class derived from 'Scope'.

101     ajvAddFormats(this._ajv);
                      ~~~~~~~~~
```

(cherry picked from commit ffbc623185d22ccfedfd9998473fa1829224f6f7)