ci: fix saucelabs unsupported OS/browser/version/device combo
```
UnsupportedOperationError: Misconfigured -- Unsupported OS/browser/version/device combo: OS: 'Mac 10.15', Browser: 'safari', Version: '13.0.', Device: 'unspecified'
```

(cherry picked from commit 5a894657e94cdf3b7d3c51f3f581e5b51da154f2)