test: remove environment variable from error dump
This is bloating the logs with in most cases not needed information and make it harder to find the actual errors.

Example output

```
Running test "tests/build/styles/stylus.ts" (8 of 27 [3:8] (60/218))...
==========================================================================================
Running `/usr/local/bin/node "/home/circleci/ng/tests/legacy-cli/e2e/utils/run_test_process" "/home/circleci/ng/tests/legacy-cli/e2e/tests/build/styles/stylus"`...
CWD: /mnt/ramdisk/e2e/e2e-test/test-project
  ==========================================================================================
  Running `ng "build" "--source-map" "--configuration=development"` [silent]...
  CWD: /mnt/ramdisk/e2e/e2e-test/test-project
  Test Process error Error: Process exit error - "ng build --source-map --configuration=development": 1...
  ENV:{
    "YARN_VERSION": "1.22.10",
    "NPM_CONFIG_PREFIX": "/mnt/ramdisk/e2e/npm-global",
    "NPM_CONFIG_USERCONFIG": "/mnt/ramdisk/e2e/.npmrc",
    "NPM_CONFIG_REGISTRY": "http://localhost:45091",
    "YARN_CONFIG_PREFIX": "/mnt/ramdisk/e2e/yarn-global",
    "CIRCLECI": "true",
    "SAUCE_TUNNEL_IDENTIFIER": "angular-337964-3",
    "SAUCE_PID_FILE": "/tmp/angular/sauce-connect-pid-file.lock",
    "SAUCE_USERNAME": "angular-tooling",
    "SAUCE_ACCESS_KEY": "e05dabf6fe0e-2c18-abf4-496d-1d010490",
    "SAUCE_LOG_FILE": "/tmp/angular/sauce-connect.log",
    "CI": "true",
    "SAUCE_READY_FILE": "/tmp/angular/sauce-connect-ready-file.lock",
    "SAUCE_READY_FILE_TIMEOUT": "120",
    "LEGACY_CLI__argv": "{\"_\":[],\"nb-shards\":8,\"shard\":3,\"tmpdir\":\"/mnt/ramdisk/e2e\",\"ignore\":\"tests/misc/browsers.ts\"}",
    "LEGACY_CLI__ci": "true",
    "LEGACY_CLI__package-manager": "\"npm\"",
    "LEGACY_CLI__package-registry": "\"http://localhost:45091\"",
    "LEGACY_CLI__package-secure-registry": "\"http://localhost:35403\"",
    "LEGACY_CLI__tmp-root": "\"/mnt/ramdisk/e2e\"",
    "LEGACY_CLI__npm-global": "\"/mnt/ramdisk/e2e/npm-global\"",
    "LEGACY_CLI__yarn-global": "\"/mnt/ramdisk/e2e/yarn-global\"",
    "LEGACY_CLI__projects-root": "\"/mnt/ramdisk/e2e/e2e-test\"",
    "PATH": "/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/home/circleci/.npm-global/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  }
  STDOUT:
  STDERR:
  Error: Schema validation failed with the following errors:
    Data path "/styles/0/input" must match pattern "\.(?:css|scss|sass|less)$".
    Data path "/styles/0" must be string.
    Data path "/styles/0" must match exactly one schema in oneOf.
      at _exec (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:76:19)
      at silentNg (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:269:12)
      at ng (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:257:16)
      at /home/circleci/ng/tests/legacy-cli/e2e/tests/build/styles/stylus.ts:29:38
      at async /home/circleci/ng/tests/legacy-cli/e2e/utils/test_process.ts:15:9
  ENV:{
    "YARN_VERSION": "1.22.10",
    "NPM_CONFIG_PREFIX": "/mnt/ramdisk/e2e/npm-global",
    "NPM_CONFIG_USERCONFIG": "/mnt/ramdisk/e2e/.npmrc",
    "NPM_CONFIG_REGISTRY": "http://localhost:45091",
    "YARN_CONFIG_PREFIX": "/mnt/ramdisk/e2e/yarn-global",
    "CIRCLECI": "true",
    "SAUCE_TUNNEL_IDENTIFIER": "angular-337964-3",
    "SAUCE_PID_FILE": "/tmp/angular/sauce-connect-pid-file.lock",
    "SAUCE_USERNAME": "angular-tooling",
    "SAUCE_ACCESS_KEY": "e05dabf6fe0e-2c18-abf4-496d-1d010490",
    "SAUCE_LOG_FILE": "/tmp/angular/sauce-connect.log",
    "CI": "true",
    "SAUCE_READY_FILE": "/tmp/angular/sauce-connect-ready-file.lock",
    "SAUCE_READY_FILE_TIMEOUT": "120",
    "LEGACY_CLI__argv": "{\"_\":[],\"nb-shards\":8,\"shard\":3,\"tmpdir\":\"/mnt/ramdisk/e2e\",\"ignore\":\"tests/misc/browsers.ts\"}",
    "LEGACY_CLI__ci": "true",
    "LEGACY_CLI__package-manager": "\"npm\"",
    "LEGACY_CLI__package-registry": "\"http://localhost:45091\"",
    "LEGACY_CLI__package-secure-registry": "\"http://localhost:35403\"",
    "LEGACY_CLI__tmp-root": "\"/mnt/ramdisk/e2e\"",
    "LEGACY_CLI__npm-global": "\"/mnt/ramdisk/e2e/npm-global\"",
    "LEGACY_CLI__yarn-global": "\"/mnt/ramdisk/e2e/yarn-global\"",
    "LEGACY_CLI__projects-root": "\"/mnt/ramdisk/e2e/e2e-test\"",
    "PATH": "/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/home/circleci/.npm-global/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  }
==========================================================================================
Running `git "clean" "-df"` [silent]...
CWD: /mnt/ramdisk/e2e/e2e-test/test-project
==========================================================================================
Running `git "reset" "--hard"` [silent]...
CWD: /mnt/ramdisk/e2e/e2e-test/test-project

Test "tests/build/styles/stylus" failed...

Process exit error - "/usr/local/bin/node /home/circleci/ng/tests/legacy-cli/e2e/utils/run_test_process /home/circleci/ng/tests/legacy-cli/e2e/tests/build/styles/stylus": 255...

ENV:{
  "YARN_VERSION": "1.22.10",
  "NPM_CONFIG_PREFIX": "/mnt/ramdisk/e2e/npm-global",
  "NPM_CONFIG_USERCONFIG": "/mnt/ramdisk/e2e/.npmrc",
  "NPM_CONFIG_REGISTRY": "http://localhost:45091",
  "YARN_CONFIG_PREFIX": "/mnt/ramdisk/e2e/yarn-global",
  "CIRCLECI": "true",
  "SAUCE_TUNNEL_IDENTIFIER": "angular-337964-3",
  "SAUCE_PID_FILE": "/tmp/angular/sauce-connect-pid-file.lock",
  "SAUCE_USERNAME": "angular-tooling",
  "SAUCE_ACCESS_KEY": "e05dabf6fe0e-2c18-abf4-496d-1d010490",
  "SAUCE_LOG_FILE": "/tmp/angular/sauce-connect.log",
  "CI": "true",
  "SAUCE_READY_FILE": "/tmp/angular/sauce-connect-ready-file.lock",
  "SAUCE_READY_FILE_TIMEOUT": "120",
  "LEGACY_CLI__argv": "{\"_\":[],\"nb-shards\":8,\"shard\":3,\"tmpdir\":\"/mnt/ramdisk/e2e\",\"ignore\":\"tests/misc/browsers.ts\"}",
  "LEGACY_CLI__ci": "true",
  "LEGACY_CLI__package-manager": "\"npm\"",
  "LEGACY_CLI__package-registry": "\"http://localhost:45091\"",
  "LEGACY_CLI__package-secure-registry": "\"http://localhost:35403\"",
  "LEGACY_CLI__tmp-root": "\"/mnt/ramdisk/e2e\"",
  "LEGACY_CLI__npm-global": "\"/mnt/ramdisk/e2e/npm-global\"",
  "LEGACY_CLI__yarn-global": "\"/mnt/ramdisk/e2e/yarn-global\"",
  "LEGACY_CLI__projects-root": "\"/mnt/ramdisk/e2e/e2e-test\"",
  "PATH": "/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/home/circleci/.npm-global/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}

STDOUT:
==========================================================================================
Running `ng "build" "--source-map" "--configuration=development"` [silent]...
CWD: /mnt/ramdisk/e2e/e2e-test/test-project

STDERR:
Test Process error Error: Process exit error - "ng build --source-map --configuration=development": 1...

ENV:{
  "YARN_VERSION": "1.22.10",
  "NPM_CONFIG_PREFIX": "/mnt/ramdisk/e2e/npm-global",
  "NPM_CONFIG_USERCONFIG": "/mnt/ramdisk/e2e/.npmrc",
  "NPM_CONFIG_REGISTRY": "http://localhost:45091",
  "YARN_CONFIG_PREFIX": "/mnt/ramdisk/e2e/yarn-global",
  "CIRCLECI": "true",
  "SAUCE_TUNNEL_IDENTIFIER": "angular-337964-3",
  "SAUCE_PID_FILE": "/tmp/angular/sauce-connect-pid-file.lock",
  "SAUCE_USERNAME": "angular-tooling",
  "SAUCE_ACCESS_KEY": "e05dabf6fe0e-2c18-abf4-496d-1d010490",
  "SAUCE_LOG_FILE": "/tmp/angular/sauce-connect.log",
  "CI": "true",
  "SAUCE_READY_FILE": "/tmp/angular/sauce-connect-ready-file.lock",
  "SAUCE_READY_FILE_TIMEOUT": "120",
  "LEGACY_CLI__argv": "{\"_\":[],\"nb-shards\":8,\"shard\":3,\"tmpdir\":\"/mnt/ramdisk/e2e\",\"ignore\":\"tests/misc/browsers.ts\"}",
  "LEGACY_CLI__ci": "true",
  "LEGACY_CLI__package-manager": "\"npm\"",
  "LEGACY_CLI__package-registry": "\"http://localhost:45091\"",
  "LEGACY_CLI__package-secure-registry": "\"http://localhost:35403\"",
  "LEGACY_CLI__tmp-root": "\"/mnt/ramdisk/e2e\"",
  "LEGACY_CLI__npm-global": "\"/mnt/ramdisk/e2e/npm-global\"",
  "LEGACY_CLI__yarn-global": "\"/mnt/ramdisk/e2e/yarn-global\"",
  "LEGACY_CLI__projects-root": "\"/mnt/ramdisk/e2e/e2e-test\"",
  "PATH": "/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/home/circleci/.npm-global/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}

STDOUT:

STDERR:
Error: Schema validation failed with the following errors:
  Data path "/styles/0/input" must match pattern "\.(?:css|scss|sass|less)$".
  Data path "/styles/0" must be string.
  Data path "/styles/0" must match exactly one schema in oneOf.

    at _exec (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:76:19)
    at silentNg (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:269:12)
    at ng (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:257:16)
    at /home/circleci/ng/tests/legacy-cli/e2e/tests/build/styles/stylus.ts:29:38
    at async /home/circleci/ng/tests/legacy-cli/e2e/utils/test_process.ts:15:9
ENV:{
  "YARN_VERSION": "1.22.10",
  "NPM_CONFIG_PREFIX": "/mnt/ramdisk/e2e/npm-global",
  "NPM_CONFIG_USERCONFIG": "/mnt/ramdisk/e2e/.npmrc",
  "NPM_CONFIG_REGISTRY": "http://localhost:45091",
  "YARN_CONFIG_PREFIX": "/mnt/ramdisk/e2e/yarn-global",
  "CIRCLECI": "true",
  "SAUCE_TUNNEL_IDENTIFIER": "angular-337964-3",
  "SAUCE_PID_FILE": "/tmp/angular/sauce-connect-pid-file.lock",
  "SAUCE_USERNAME": "angular-tooling",
  "SAUCE_ACCESS_KEY": "e05dabf6fe0e-2c18-abf4-496d-1d010490",
  "SAUCE_LOG_FILE": "/tmp/angular/sauce-connect.log",
  "CI": "true",
  "SAUCE_READY_FILE": "/tmp/angular/sauce-connect-ready-file.lock",
  "SAUCE_READY_FILE_TIMEOUT": "120",
  "LEGACY_CLI__argv": "{\"_\":[],\"nb-shards\":8,\"shard\":3,\"tmpdir\":\"/mnt/ramdisk/e2e\",\"ignore\":\"tests/misc/browsers.ts\"}",
  "LEGACY_CLI__ci": "true",
  "LEGACY_CLI__package-manager": "\"npm\"",
  "LEGACY_CLI__package-registry": "\"http://localhost:45091\"",
  "LEGACY_CLI__package-secure-registry": "\"http://localhost:35403\"",
  "LEGACY_CLI__tmp-root": "\"/mnt/ramdisk/e2e\"",
  "LEGACY_CLI__npm-global": "\"/mnt/ramdisk/e2e/npm-global\"",
  "LEGACY_CLI__yarn-global": "\"/mnt/ramdisk/e2e/yarn-global\"",
  "LEGACY_CLI__projects-root": "\"/mnt/ramdisk/e2e/e2e-test\"",
  "PATH": "/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/home/circleci/.npm-global/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}

Error: Process exit error - "/usr/local/bin/node /home/circleci/ng/tests/legacy-cli/e2e/utils/run_test_process /home/circleci/ng/tests/legacy-cli/e2e/tests/build/styles/stylus": 255...

ENV:{
  "YARN_VERSION": "1.22.10",
  "NPM_CONFIG_PREFIX": "/mnt/ramdisk/e2e/npm-global",
  "NPM_CONFIG_USERCONFIG": "/mnt/ramdisk/e2e/.npmrc",
  "NPM_CONFIG_REGISTRY": "http://localhost:45091",
  "YARN_CONFIG_PREFIX": "/mnt/ramdisk/e2e/yarn-global",
  "CIRCLECI": "true",
  "SAUCE_TUNNEL_IDENTIFIER": "angular-337964-3",
  "SAUCE_PID_FILE": "/tmp/angular/sauce-connect-pid-file.lock",
  "SAUCE_USERNAME": "angular-tooling",
  "SAUCE_ACCESS_KEY": "e05dabf6fe0e-2c18-abf4-496d-1d010490",
  "SAUCE_LOG_FILE": "/tmp/angular/sauce-connect.log",
  "CI": "true",
  "SAUCE_READY_FILE": "/tmp/angular/sauce-connect-ready-file.lock",
  "SAUCE_READY_FILE_TIMEOUT": "120",
  "LEGACY_CLI__argv": "{\"_\":[],\"nb-shards\":8,\"shard\":3,\"tmpdir\":\"/mnt/ramdisk/e2e\",\"ignore\":\"tests/misc/browsers.ts\"}",
  "LEGACY_CLI__ci": "true",
  "LEGACY_CLI__package-manager": "\"npm\"",
  "LEGACY_CLI__package-registry": "\"http://localhost:45091\"",
  "LEGACY_CLI__package-secure-registry": "\"http://localhost:35403\"",
  "LEGACY_CLI__tmp-root": "\"/mnt/ramdisk/e2e\"",
  "LEGACY_CLI__npm-global": "\"/mnt/ramdisk/e2e/npm-global\"",
  "LEGACY_CLI__yarn-global": "\"/mnt/ramdisk/e2e/yarn-global\"",
  "LEGACY_CLI__projects-root": "\"/mnt/ramdisk/e2e/e2e-test\"",
  "PATH": "/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/home/circleci/.npm-global/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}

STDOUT:
==========================================================================================
Running `ng "build" "--source-map" "--configuration=development"` [silent]...
CWD: /mnt/ramdisk/e2e/e2e-test/test-project

STDERR:
Test Process error Error: Process exit error - "ng build --source-map --configuration=development": 1...

ENV:{
  "YARN_VERSION": "1.22.10",
  "NPM_CONFIG_PREFIX": "/mnt/ramdisk/e2e/npm-global",
  "NPM_CONFIG_USERCONFIG": "/mnt/ramdisk/e2e/.npmrc",
  "NPM_CONFIG_REGISTRY": "http://localhost:45091",
  "YARN_CONFIG_PREFIX": "/mnt/ramdisk/e2e/yarn-global",
  "CIRCLECI": "true",
  "SAUCE_TUNNEL_IDENTIFIER": "angular-337964-3",
  "SAUCE_PID_FILE": "/tmp/angular/sauce-connect-pid-file.lock",
  "SAUCE_USERNAME": "angular-tooling",
  "SAUCE_ACCESS_KEY": "e05dabf6fe0e-2c18-abf4-496d-1d010490",
  "SAUCE_LOG_FILE": "/tmp/angular/sauce-connect.log",
  "CI": "true",
  "SAUCE_READY_FILE": "/tmp/angular/sauce-connect-ready-file.lock",
  "SAUCE_READY_FILE_TIMEOUT": "120",
  "LEGACY_CLI__argv": "{\"_\":[],\"nb-shards\":8,\"shard\":3,\"tmpdir\":\"/mnt/ramdisk/e2e\",\"ignore\":\"tests/misc/browsers.ts\"}",
  "LEGACY_CLI__ci": "true",
  "LEGACY_CLI__package-manager": "\"npm\"",
  "LEGACY_CLI__package-registry": "\"http://localhost:45091\"",
  "LEGACY_CLI__package-secure-registry": "\"http://localhost:35403\"",
  "LEGACY_CLI__tmp-root": "\"/mnt/ramdisk/e2e\"",
  "LEGACY_CLI__npm-global": "\"/mnt/ramdisk/e2e/npm-global\"",
  "LEGACY_CLI__yarn-global": "\"/mnt/ramdisk/e2e/yarn-global\"",
  "LEGACY_CLI__projects-root": "\"/mnt/ramdisk/e2e/e2e-test\"",
  "PATH": "/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/home/circleci/.npm-global/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}

STDOUT:

STDERR:
Error: Schema validation failed with the following errors:
  Data path "/styles/0/input" must match pattern "\.(?:css|scss|sass|less)$".
  Data path "/styles/0" must be string.
  Data path "/styles/0" must match exactly one schema in oneOf.

    at _exec (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:76:19)
    at silentNg (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:269:12)
    at ng (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:257:16)
    at /home/circleci/ng/tests/legacy-cli/e2e/tests/build/styles/stylus.ts:29:38
    at async /home/circleci/ng/tests/legacy-cli/e2e/utils/test_process.ts:15:9
ENV:{
  "YARN_VERSION": "1.22.10",
  "NPM_CONFIG_PREFIX": "/mnt/ramdisk/e2e/npm-global",
  "NPM_CONFIG_USERCONFIG": "/mnt/ramdisk/e2e/.npmrc",
  "NPM_CONFIG_REGISTRY": "http://localhost:45091",
  "YARN_CONFIG_PREFIX": "/mnt/ramdisk/e2e/yarn-global",
  "CIRCLECI": "true",
  "SAUCE_TUNNEL_IDENTIFIER": "angular-337964-3",
  "SAUCE_PID_FILE": "/tmp/angular/sauce-connect-pid-file.lock",
  "SAUCE_USERNAME": "angular-tooling",
  "SAUCE_ACCESS_KEY": "e05dabf6fe0e-2c18-abf4-496d-1d010490",
  "SAUCE_LOG_FILE": "/tmp/angular/sauce-connect.log",
  "CI": "true",
  "SAUCE_READY_FILE": "/tmp/angular/sauce-connect-ready-file.lock",
  "SAUCE_READY_FILE_TIMEOUT": "120",
  "LEGACY_CLI__argv": "{\"_\":[],\"nb-shards\":8,\"shard\":3,\"tmpdir\":\"/mnt/ramdisk/e2e\",\"ignore\":\"tests/misc/browsers.ts\"}",
  "LEGACY_CLI__ci": "true",
  "LEGACY_CLI__package-manager": "\"npm\"",
  "LEGACY_CLI__package-registry": "\"http://localhost:45091\"",
  "LEGACY_CLI__package-secure-registry": "\"http://localhost:35403\"",
  "LEGACY_CLI__tmp-root": "\"/mnt/ramdisk/e2e\"",
  "LEGACY_CLI__npm-global": "\"/mnt/ramdisk/e2e/npm-global\"",
  "LEGACY_CLI__yarn-global": "\"/mnt/ramdisk/e2e/yarn-global\"",
  "LEGACY_CLI__projects-root": "\"/mnt/ramdisk/e2e/e2e-test\"",
  "PATH": "/mnt/ramdisk/e2e/yarn-global/bin:/mnt/ramdisk/e2e/npm-global/bin:/home/circleci/.npm-global/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}

    at _exec (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:76:19)
    at launchTestProcess (/home/circleci/ng/tests/legacy-cli/e2e/utils/process.ts:333:12)
    at runTest (/home/circleci/ng/tests/legacy-cli/e2e_runner.ts:263:47)
    at runSteps (/home/circleci/ng/tests/legacy-cli/e2e_runner.ts:232:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/circleci/ng/tests/legacy-cli/e2e_runner.ts:183:9

Exited with code exit status 1
CircleCI received exit code 1
```

(cherry picked from commit d974bbb6c4d2c693e76ff86bcfd67b3f2d417bdb)