build: rename `typings.d.ts` to `typings.ts`
Fixes
```
ERROR: /home/circleci/ng/packages/angular/cli/BUILD.bazel:289:11: Compiling TypeScript (devmode) //packages/angular/cli:angular-cli_test_lib failed: (Exit 1): tsc_wrapped.sh failed: error executing command
  (cd /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular_cli && \
  exec env - \
    NG_FORCE_TTY=false \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh @@bazel-out/k8-fastbuild/bin/packages/angular/cli/angular-cli_test_lib_es5_tsconfig.json)
Execution platform: //tools:rbe_platform_with_network_access
error TS5055: Cannot write file '/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular_cli/bazel-out/k8-fastbuild/bin/packages/angular/cli/utilities/package-metadata.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
```