feat(universal): AOT support (#560)
* feat(universal): AOT support (WIP)

* Additional updates for AOT/ngc support

These udpates resolve issues when using ngc from a parent reposistory pulling in the
ngc compiled code from universal

* Remove all @internal tags

Without this update ngc cannot compile the ngfactory precompiled code from universal.
Anything tagged with @internal will throw error:
    Error: can't find symbol [class or function name] exported from module

* Add back src/ folder removal with gulp streams

* Specify exports when removing src folder

This works around compile errors caused by ambiguities of
export * from './browser' in browser.js when there is also a
./browser/index.js. This is important when importing from, for example,
angular2-universal/browser or angular2-universal/node

* Set skinInternal to false in tsconfig and add back @internal tags

* Add back __private_imports__ now that we have skipInternal set to false

* Consolidate tsconfigs to one file and fix paths to allow import instead of require for angular2-univeral/node

* Resolve NodeJsonpBackend_ interface incompatibility errors