fix(commands): fix outdated string utils import.
* Currently the command `ng make-this-awesome` is not working, because the stringUtils, for the camelize function are not loaded correctly.

> Cannot find module 'angular-cli/lib/utilities/string'
> Error: Cannot find module 'angular-cli/lib/utilities/string'