fix(@angular/cli): use headless option in MCP test tool
This avoids the following error for projects using Vitest and Browser mode:

```
 Unhandled Error:
  Error: [(chrome)] Browser "chrome" is not supported by the browser provider "playwright". Supported
  browsers: firefox, webkit, chromium.
```

(cherry picked from commit 0d984cf1cdfed0a4f74e6bf8efb8a3c999ebc373)