Jasmine types and jasmine-core are out of sync
Jasmine-types are right now on latest version and have the new matchers
`toBeGreaterThanOrEqual` and `toBeLessThanOrEqual` (see https://github.com/jasmine/jasmine/commit/b7d8b0de713b5a123b73d026a03849d3f5dffb0d / https://github.com/jasmine/jasmine/issues/1013 )

Unfortunately current jasmine is pinned to `2.4.1`, so promised matchers are not available and lead to following errors:

```
 TypeError: expect(...).toBeGreaterThanOrEqual is not a function
 TypeError: expect(...).toBeLessThanOrEqual is not a function
```