build: force resolution of `@types/copy-webpack-plugin/webpack`
This resolution is needed as otherwise if webpack versions are not on the exact version the compilation will fail.

Example of such errors;
```
packages/angular_devkit/build_angular/src/webpack/configs/common.ts:219:7 - error TS2345: Argument of type 'CopyPlugin' is not assignable to parameter of type '{ apply(compiler: Compiler): void; }'.
  Types of property 'apply' are incompatible.
    Type '(compiler: import("/home/circleci/ng/node_modules/@types/copy-webpack-plugin/node_modules/webpack/types").Compiler) => void' is not assignable to type '(compiler: import("/home/circleci/ng/node_modules/webpack/types").Compiler) => void'.
      Types of parameters 'compiler' and 'compiler' are incompatible.
        Type 'import("/home/circleci/ng/node_modules/webpack/types").Compiler' is not assignable to type 'import("/home/circleci/ng/node_modules/@types/copy-webpack-plugin/node_modules/webpack/types").Compiler'.
          The types of 'hooks.shouldEmit' are incompatible between these types.
            Type 'import("/home/circleci/ng/node_modules/tapable/tapable").SyncBailHook<[import("/home/circleci/ng/node_modules/webpack/types").Compilation], boolean, import("/home/circleci/ng/node_modules/tapable/tapable").UnsetAdditionalOptions>' is not assignable to type 'import("/home/circleci/ng/node_modules/tapable/tapable").SyncBailHook<[import("/home/circleci/ng/node_modules/@types/copy-webpack-plugin/node_modules/webpack/types").Compilation], boolean, import("/home/circleci/ng/node_modules/tapable/tapable").UnsetAdditionalOptions>'.

219       new CopyWebpackPlugin({
          ~~~~~~~~~~~~~~~~~~~~~~~
220         patterns: copyWebpackPluginPatterns,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
221       }),
    ~~~~~~~~
```

(cherry picked from commit fdbbcfd79ebf89bd860dac9903c69c6c45f5b834)